version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"
  apt_packages:
    - autoconf
    - enchant-2
    - hunspell-en-us
    - make
  jobs:
    # Doc requires to have ltp.json
    pre_build:
      - make autotools
      - ./configure
      - make -C metadata/

# Build from the doc/ directory with Sphinx
sphinx:
  configuration: doc/conf.py

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: doc/requirements.txt
